/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Hoadon;
import Model.Khachhang;
import Model.Mathang;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRINCE D. TOAD
 */
public class ViewHoadon extends javax.swing.JFrame {

    private List<Khachhang> listKH;
    private List<Mathang> listMH;
    private DefaultTableModel defaultTableModel;
    private List<Pair<Mathang, Integer>> listSLMH;
    private int stt = 0;
    private float tongtien = 0;
    private Hoadon hd;

    /**
     * Creates new form ViewHoadon
     */
    public ViewHoadon(List<Khachhang> listKH, List<Mathang> listMH) {
        initComponents();
        this.listKH = listKH;
        this.listMH = listMH;
        listSLMH = new ArrayList<>();

        defaultTableModel = (DefaultTableModel) tblMH.getModel();
        tblMH.setModel(defaultTableModel);

        getListKHToCombobox();
        getListMHToCombobox();
    }

    private void getListKHToCombobox() {
        for (Khachhang kh : listKH) {
            cbKH.addItem(kh.toString());
        }
//        cbKH.setSelectedIndex(0);
    }

    private void getListMHToCombobox() {
        for (Mathang mh : listMH) {
            cbMH.addItem(mh.toString());
        }
//        cbMH.setSelectedIndex(0);
    }

    private Mathang searchMathang(String tenMH) {
        for (Mathang mh : listMH) {
            if (mh.getTenMH().equals(tenMH)) {
                return mh;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbKH = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbMH = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        txtSoluong = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMH = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tạo hóa đơn");

        jLabel2.setText("Nhap ma hoa don :");

        jLabel3.setText("Chon khach hang :");

        jLabel4.setText("Them mat hang :");

        jButton1.setText("Them MH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tao hoa don");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ma MH", "Ten MH", "So luong mua", "Gia tien"
            }
        ));
        jScrollPane1.setViewportView(tblMH);

        jLabel5.setText("Tong tien :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHD)
                    .addComponent(cbKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbMH, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtSoluong.getText().toString().equals("")) {

        } else {
            Mathang mh = searchMathang((String) cbMH.getSelectedItem());
            // tong gia tien khi mua san pham
            BigDecimal giatien = new BigDecimal(Integer.parseInt(
                    txtSoluong.getText().toString()) * mh.getGiaban());
            giatien = giatien.add(BigDecimal.ZERO);

            Pair<Mathang, Integer> slmh = new Pair<Mathang, Integer>(mh,
                    Integer.parseInt(txtSoluong.getText().toString()));
            listSLMH.add(slmh);
            defaultTableModel.addRow(new Object[]{
                ++stt,
                mh.getMaMH(),
                mh.getTenMH(),
                txtSoluong.getText().toString(),
                giatien
            });

            // tinh tong tien hoa don
            tongtien += Integer.parseInt(
                    txtSoluong.getText().toString()) * mh.getGiaban();
            BigDecimal bigTongtien = new BigDecimal(tongtien);
            bigTongtien = bigTongtien.add(BigDecimal.ZERO);
            txtTongtien.setText(String.valueOf(bigTongtien));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!txtMaHD.getText().toString().equals("") && listSLMH.size() > 0) {
            hd = new Hoadon();
            Khachhang kh = new Khachhang();
            kh.setHoten((String) cbKH.getSelectedItem());
            hd.setMaHD(Integer.parseInt(txtMaHD.getText().toString()));
            hd.setKhachhang(kh);
            hd.setListMH(listSLMH);
            hd.setTongTien(tongtien);

            // Lay ngay hien tai
            Date date = new Date(System.currentTimeMillis());
            SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss dd/MM/yyyy");
            String s = dateFormat.format(date.getTime());
            hd.setNgaytao(s);

            ghiFile();

            ViewXemHoadon xemHoadon = new ViewXemHoadon(hd);
            xemHoadon.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ghiFile() {
        try {
            File file = new File("HD.INP");
            
            FileWriter fw = new FileWriter(file, true);
            fw.write(hd.getMaHD() + "" + "\n");
            fw.write(hd.getKhachhang().getHoten() + "\n");
            fw.write(hd.getNgaytao() + "\n");
            for (Pair<Mathang, Integer> slmh : listSLMH) {
                BigDecimal bigGiaTien = new BigDecimal(slmh.getKey().getGiaban()
                        * slmh.getValue());
                fw.write(slmh.getKey().getTenMH()
                        + " " + slmh.getValue() + " " + bigGiaTien + "\n");
            }
            BigDecimal bigTongTien = new BigDecimal(hd.getTongTien());
            fw.write(bigTongTien + "\n");

            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(ViewHoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbKH;
    private javax.swing.JComboBox cbMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMH;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JLabel txtTongtien;
    // End of variables declaration//GEN-END:variables
}
